require 'huginn_agent'

#HuginnAgent.load 'huginn_geforcenow_region_status_agent/concerns/my_agent_concern'
HuginnAgent.register 'huginn_geforcenow_region_status_agent/geforcenow_region_status_agent'
